{{- $selectorLabels := include "kubeblocks.selectorLabels" . }}
{{- include "kubeblocks.buildAddonCR" (merge (dict
  "kbVersion" ">=0.8.0 <0.9.0"
  "selectorLabels" $selectorLabels
  "name" "polardb-mongo-compat"
  "version" "0.8.0"
  "model" "document"
  "provider" "community"
  "description" "MongoDB-compatible API addon backed by PostgreSQL DocumentDB and FerretDB."
  "autoInstall" false) . ) -}}
