name: PULL-REQUEST-CHECK

on:
  pull_request_target:
    types: [ edited, opened ]

permissions:
  issues: read
  pull-requests: read

jobs:
  pr-check:
    name: PR Pre-Check
    if: ${{ !(startsWith(github.head_ref, 'releasing-') && startsWith(github.base_ref, 'release-')) }}
    runs-on: ubuntu-latest
    steps:
      - name: check branch name
        if: github.event.pull_request.head.repo.full_name == github.repository
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          branch_pattern='^(feature/|bugfix/|release/|hotfix/|support/|releasing/|dependabot/)'
          ignore_branch_pattern='^(main|master)$'

          if [[ "$HEAD_REF" =~ $ignore_branch_pattern ]]; then
            echo "This branch should be ignored"
            exit 0
          fi

          if [[ "$HEAD_REF" =~ $branch_pattern ]]; then
            echo "This branch has a valid name"
            exit 0
          fi

          echo "::error::This branch name is not following the standards: feature/|bugfix/|release/|hotfix/|support/|releasing/|dependabot/"
          exit 1

      - name: check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check issue link
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$PR_TITLE" == chore* || "$PR_TITLE" == docs* ]]; then
            echo "PR skip the issue check"
            exit 0
          fi

          repo_name="${REPO/${REPO_OWNER}\//}"
          closing_issues_references="$(
            gh api graphql \
              -f owner="$REPO_OWNER" \
              -f name="$repo_name" \
              -F number="$PR_NUMBER" \
              -f query='
                query($owner: String!, $name: String!, $number: Int!) {
                  repository(owner: $owner, name: $name) {
                    pullRequest(number: $number) {
                      closingIssuesReferences(first: 10) {
                        edges {
                          node {
                            title
                            number
                          }
                        }
                      }
                    }
                  }
                }' \
              --jq '.data.repository.pullRequest.closingIssuesReferences.edges'
          )"

          echo "Closing Issues References: $closing_issues_references"

          if [[ "$closing_issues_references" == "[]" ]]; then
            echo "PR has no Issues References"
            exit 1
          fi

          echo "PR has Issues References"
